// Meme Generator input contract. Documentation artifact; backend mirrors this with Pydantic.

export type MemeEventSource =
  | "MANUAL"
  | "COMMENTARY_EVENT"
  | "HIGHLIGHT"
  | "GAME_CONNECTOR"
  | "TRANSCRIPT";

export type MemeMomentType =
  | "FAILURE"
  | "SUCCESS"
  | "BETRAYAL"
  | "TEAM_EVENT"
  | "MILESTONE"
  | "PREPARATION"
  | "NAVIGATION"
  | "PANIC"
  | "SILENCE"
  | "MANUAL_NOTE";

export interface MemeGameContext {
  gameKey: string;
  matchId?: string;
  roundId?: string;
  mode?: string;
  map?: string;
}

export interface MemeEventV1 {
  schemaVersion: "1.0";
  /** UUID generated by the caller; retrying it is idempotent within the server. */
  eventId: string;
  serverId: number;
  sessionId?: string;
  source: MemeEventSource;
  occurredAt: string;
  momentType: MemeMomentType;
  actorPlayerIds: string[];
  targetPlayerIds: string[];
  game: MemeGameContext;
  /** Factual one-sentence event summary, maximum 240 chars. */
  summary: string;
  /** Optional explicit setup/payoff; neither field may add facts absent from the source. */
  setup?: string;
  payoff?: string;
  importance: number;
  confidence: number;
  /** Server-owned asset; arbitrary paths and URLs are not accepted. */
  screenshotAssetId?: string;
  facts?: Array<{
    key: "durationSeconds" | "attemptCount" | "itemsLost" | "healthRemaining" | "teamSize";
    value: string | number | boolean;
  }>;
}

export const uselessPreparationExample: MemeEventV1 = {
  schemaVersion: "1.0",
  eventId: "fce32b68-29fc-4443-9a8b-56e9d2917807",
  serverId: 4,
  sessionId: "79a68cf4-4340-4e44-8c8a-1a1264a2358c",
  source: "MANUAL",
  occurredAt: "2026-08-04T20:14:32Z",
  momentType: "PREPARATION",
  actorPlayerIds: ["player_2"],
  targetPlayerIds: [],
  game: { gameKey: "survival-game", matchId: "match-108" },
  summary: "player_2 on dakika eşya topladıktan sonra ilk engelde düşüp hepsini kaybetti.",
  setup: "On dakika boyunca eşya topladı.",
  payoff: "İlk engelde düşüp bütün eşyaları kaybetti.",
  importance: 0.82,
  confidence: 1,
  facts: [
    { key: "durationSeconds", value: 600 },
    { key: "itemsLost", value: 18 },
  ],
};

