"""Add Shared Story safety, snapshots, actions and sealed votes."""
from alembic import op
import sqlalchemy as sa
revision = "0018_shared_story"; down_revision = "0017_hidden_role_game"; branch_labels = None; depends_on = None
def upgrade() -> None:
    op.create_table("story_safety_profiles", sa.Column("server_id", sa.Integer(), sa.ForeignKey("servers.id", ondelete="CASCADE"), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), primary_key=True), sa.Column("horror_level", sa.Integer(), nullable=False, server_default="1"), sa.Column("violence_level", sa.Integer(), nullable=False, server_default="1"), sa.Column("romance", sa.String(16), nullable=False, server_default="OFF"), sa.Column("player_conflict", sa.String(16), nullable=False, server_default="COOPERATIVE"), sa.Column("betrayal", sa.String(16), nullable=False, server_default="OFF"), sa.Column("personal_jokes", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("dark_humor", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("version", sa.Integer(), nullable=False, server_default="1"), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("story_characters", sa.Column("session_id", sa.String(36), sa.ForeignKey("experience_sessions.id", ondelete="CASCADE"), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), primary_key=True), sa.Column("seat", sa.Integer(), nullable=False), sa.Column("name", sa.String(60), nullable=False), sa.Column("archetype", sa.String(32), nullable=False), sa.Column("traits", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("story_states", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("session_id", sa.String(36), sa.ForeignKey("experience_sessions.id", ondelete="CASCADE"), nullable=False), sa.Column("revision", sa.Integer(), nullable=False), sa.Column("is_current", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("public_state", sa.JSON(), nullable=False), sa.Column("private_state_ciphertext", sa.LargeBinary(), nullable=False), sa.Column("rng_counter", sa.Integer(), nullable=False, server_default="0"), sa.Column("rng_commitment", sa.String(64), nullable=False), sa.Column("reason", sa.String(20), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("session_id", "revision", name="uq_story_state_revision")); op.create_index("ix_story_state_current", "story_states", ["session_id", "is_current"])
    op.create_table("story_actions", sa.Column("id", sa.String(36), primary_key=True), sa.Column("session_id", sa.String(36), sa.ForeignKey("experience_sessions.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("chapter_number", sa.Integer(), nullable=False), sa.Column("scene_number", sa.Integer(), nullable=False), sa.Column("idempotency_key", sa.String(128), nullable=False), sa.Column("action_id", sa.String(80), nullable=False), sa.Column("outcome", sa.String(24), nullable=False), sa.Column("effect_payload", sa.JSON(), nullable=False), sa.Column("applied_revision", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("session_id", "user_id", "idempotency_key", name="uq_story_action_idempotency"))
    op.create_table("story_choice_votes", sa.Column("id", sa.String(36), primary_key=True), sa.Column("session_id", sa.String(36), sa.ForeignKey("experience_sessions.id", ondelete="CASCADE"), nullable=False), sa.Column("chapter_number", sa.Integer(), nullable=False), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("encrypted_choice", sa.LargeBinary(), nullable=False), sa.Column("choice_commitment", sa.String(64), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("session_id", "chapter_number", "user_id", name="uq_story_vote_chapter_user"))
def downgrade() -> None:
    op.drop_table("story_choice_votes"); op.drop_table("story_actions"); op.drop_index("ix_story_state_current", table_name="story_states"); op.drop_table("story_states"); op.drop_table("story_characters"); op.drop_table("story_safety_profiles")
