"""Add NADIR-3 Escape Room state, attempts, private consoles and hints."""
from alembic import op
import sqlalchemy as sa
revision="0019_ai_escape_room";down_revision="0018_shared_story";branch_labels=None;depends_on=None
def upgrade()->None:
    op.create_table("escape_room_states",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("session_id",sa.String(36),sa.ForeignKey("experience_sessions.id",ondelete="CASCADE"),nullable=False),sa.Column("revision",sa.Integer(),nullable=False),sa.Column("is_current",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("public_state",sa.JSON(),nullable=False),sa.Column("engine_ciphertext",sa.LargeBinary(),nullable=False),sa.Column("rng_commitment",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("session_id","revision",name="uq_escape_state_revision"));op.create_index("ix_escape_state_current","escape_room_states",["session_id","is_current"])
    op.create_table("escape_private_consoles",sa.Column("session_id",sa.String(36),sa.ForeignKey("experience_sessions.id",ondelete="CASCADE"),primary_key=True),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="CASCADE"),primary_key=True),sa.Column("role",sa.String(16),nullable=False),sa.Column("encrypted_payload",sa.LargeBinary(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("escape_attempts",sa.Column("id",sa.String(36),primary_key=True),sa.Column("session_id",sa.String(36),sa.ForeignKey("experience_sessions.id",ondelete="CASCADE"),nullable=False),sa.Column("node_id",sa.String(8),nullable=False),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("idempotency_key",sa.String(128),nullable=False),sa.Column("answer_hash",sa.String(64),nullable=False),sa.Column("result",sa.String(20),nullable=False),sa.Column("state_revision",sa.Integer(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("session_id","user_id","idempotency_key",name="uq_escape_attempt_idempotency"));op.create_index("ix_escape_attempt_duplicate","escape_attempts",["session_id","node_id","user_id","answer_hash"])
    op.create_table("escape_simultaneous_submissions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("session_id",sa.String(36),sa.ForeignKey("experience_sessions.id",ondelete="CASCADE"),nullable=False),sa.Column("node_id",sa.String(8),nullable=False),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("encrypted_value",sa.LargeBinary(),nullable=False),sa.Column("value_hash",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("session_id","node_id","user_id",name="uq_escape_sim_submission_user"))
    op.create_table("escape_hint_deliveries",sa.Column("id",sa.String(36),primary_key=True),sa.Column("session_id",sa.String(36),sa.ForeignKey("experience_sessions.id",ondelete="CASCADE"),nullable=False),sa.Column("node_id",sa.String(8),nullable=False),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("tier",sa.Integer(),nullable=False),sa.Column("text",sa.String(400),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("session_id","node_id","user_id","tier",name="uq_escape_hint_delivery"))
    op.create_table("escape_final_assist_consents",sa.Column("id",sa.String(36),primary_key=True),sa.Column("session_id",sa.String(36),sa.ForeignKey("experience_sessions.id",ondelete="CASCADE"),nullable=False),sa.Column("node_id",sa.String(8),nullable=False),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("session_id","node_id","user_id",name="uq_escape_assist_consent"))
def downgrade()->None:
    op.drop_table("escape_final_assist_consents");op.drop_table("escape_hint_deliveries");op.drop_table("escape_simultaneous_submissions");op.drop_index("ix_escape_attempt_duplicate",table_name="escape_attempts");op.drop_table("escape_attempts");op.drop_table("escape_private_consoles");op.drop_index("ix_escape_state_current",table_name="escape_room_states");op.drop_table("escape_room_states")
