[CmdletBinding()]
param(
    [ValidateSet(
        'Help', 'Configure', 'Initialize', 'Validate', 'Deploy', 'Update',
        'Start', 'Stop', 'Restart', 'Status', 'Diagnose', 'Backup', 'RepairDatabase'
    )]
    [string]$Action = 'Help',
    [string]$ServerAddress,
    [string]$AcmeEmail,
    [string]$AiGatewayUrl,
    [string]$AiGatewayApiKey,
    [string]$TurnExternalAddress,
    [ValidateRange(1, 65535)]
    [int]$HttpPort = 8080,
    [ValidateRange(1, 65535)]
    [int]$HttpsPort = 8443,
    [switch]$SkipBuild
)

$ErrorActionPreference = 'Stop'
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
Set-Location $repoRoot
$envPath = Join-Path $repoRoot '.env'

function Write-Step {
    param([string]$Message)
    Write-Host "`n==> $Message" -ForegroundColor Cyan
}

function Invoke-Checked {
    param(
        [Parameter(Mandatory = $true)][string]$FilePath,
        [Parameter(Mandatory = $true)][string[]]$Arguments,
        [switch]$Capture
    )

    $output = & $FilePath @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Command failed: $FilePath $($Arguments -join ' ') (exit=$LASTEXITCODE)"
    }
    if ($Capture) {
        return (($output | Out-String).Trim())
    }
}

function Invoke-Compose {
    param([Parameter(Mandatory = $true)][string[]]$Arguments, [switch]$Capture)
    return Invoke-Checked -FilePath 'docker' -Arguments (@('compose') + $Arguments) -Capture:$Capture
}

function Get-GitExecutable {
    $git = Get-Command git -ErrorAction SilentlyContinue
    if ($git) { return $git.Source }

    $candidates = @(
        "$env:ProgramFiles\Git\cmd\git.exe",
        "${env:ProgramFiles(x86)}\Git\cmd\git.exe",
        "$env:LOCALAPPDATA\Programs\Git\cmd\git.exe"
    )
    foreach ($candidate in $candidates) {
        if ($candidate -and (Test-Path -LiteralPath $candidate)) { return $candidate }
    }
    throw 'Git was not found. Install Git for Windows first.'
}

function Assert-Prerequisites {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        throw 'Docker was not found. Install/start Docker Desktop first.'
    }
    Invoke-Checked -FilePath 'docker' -Arguments @('compose', 'version') | Out-Null
    [void](Get-GitExecutable)
}

function New-RandomSecret {
    param([int]$ByteCount = 36)
    $bytes = New-Object byte[] $ByteCount
    $rng = [Security.Cryptography.RandomNumberGenerator]::Create()
    try { $rng.GetBytes($bytes) } finally { $rng.Dispose() }
    return [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')
}

function Read-SecretValue {
    param([string]$Prompt)
    $secure = Read-Host $Prompt -AsSecureString
    $pointer = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try {
        return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($pointer)
    }
    finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($pointer)
    }
}

function Assert-ServerAddress {
    param([string]$Value)
    if ([string]::IsNullOrWhiteSpace($Value) -or $Value -match '://|/|\s') {
        throw 'ServerAddress must be an IP address or DNS name without protocol/path.'
    }
}

function Get-PublicUrl {
    param([string]$HostName, [int]$Port)
    if ($Port -eq 443) { return "https://$HostName" }
    return "https://${HostName}:$Port"
}

function New-EnvironmentFile {
    if (Test-Path -LiteralPath $envPath) {
        throw ".env already exists and was not overwritten: $envPath"
    }
    Assert-ServerAddress $ServerAddress
    if ([string]::IsNullOrWhiteSpace($AcmeEmail) -or $AcmeEmail -notmatch '@') {
        throw 'AcmeEmail is required.'
    }
    if ([string]::IsNullOrWhiteSpace($AiGatewayUrl) -or $AiGatewayUrl -notmatch '^https?://') {
        throw 'AiGatewayUrl must start with http:// or https://.'
    }
    if ([string]::IsNullOrWhiteSpace($AiGatewayApiKey)) {
        $AiGatewayApiKey = $env:NEXUS_SETUP_AI_GATEWAY_API_KEY
    }
    if ([string]::IsNullOrWhiteSpace($AiGatewayApiKey)) {
        $AiGatewayApiKey = Read-SecretValue 'Existing AI Gateway API key'
    }
    if ([string]::IsNullOrWhiteSpace($AiGatewayApiKey) -or $AiGatewayApiKey.Length -lt 32) {
        throw 'AiGatewayApiKey must contain the existing AI Gateway key (at least 32 characters).'
    }
    if ([string]::IsNullOrWhiteSpace($TurnExternalAddress)) {
        $TurnExternalAddress = $ServerAddress
    }

    $publicUrl = Get-PublicUrl -HostName $ServerAddress -Port $HttpsPort
    $matrixAuthority = if ($HttpsPort -eq 443) { "${ServerAddress}:443" } else { "${ServerAddress}:$HttpsPort" }
    $content = @"
# Generated by scripts/nexus-server.ps1. Do not commit this file.
POSTGRES_ADMIN_USER=postgres
POSTGRES_ADMIN_PASSWORD=$(New-RandomSecret)
POSTGRES_USER=nexus
POSTGRES_PASSWORD=$(New-RandomSecret)
POSTGRES_DB=nexus
POSTGRES_HOST=postgres
POSTGRES_PORT=5432

SYNAPSE_POSTGRES_USER=synapse
SYNAPSE_POSTGRES_PASSWORD=$(New-RandomSecret)
SYNAPSE_POSTGRES_DB=synapse

CORE_API_SECRET_KEY=$(New-RandomSecret)

NEXUS_DOMAIN=$ServerAddress
NEXUS_ACME_EMAIL=$AcmeEmail
NEXUS_HTTP_PORT=$HttpPort
NEXUS_HTTPS_PORT=$HttpsPort
NEXUS_PUBLIC_URL=$publicUrl
NEXUS_MATRIX_SERVER_AUTHORITY=$matrixAuthority

MATRIX_SERVER_NAME=$ServerAddress
MATRIX_HOMESERVER_URL=$publicUrl
MATRIX_REGISTRATION_SHARED_SECRET=$(New-RandomSecret)
MATRIX_MACAROON_SECRET_KEY=$(New-RandomSecret)
MATRIX_FORM_SECRET=$(New-RandomSecret)

OLLAMA_BASE_URL=$AiGatewayUrl
OLLAMA_API_KEY=$AiGatewayApiKey
OLLAMA_DEFAULT_MODEL=qwen2.5:7b
OLLAMA_CONNECT_TIMEOUT_SECONDS=5
OLLAMA_READ_TIMEOUT_SECONDS=120
OLLAMA_MAX_RETRIES=2
OLLAMA_RETRY_BACKOFF_SECONDS=0.5
OLLAMA_MODEL_CACHE_SECONDS=30

AI_WORKER_POLL_SECONDS=0.5
AI_WORKER_LEASE_SECONDS=300
AI_WORKER_MAX_ATTEMPTS=3
AI_WORKER_RETRY_BACKOFF_SECONDS=2.0
AI_MAX_PENDING_JOBS_PER_USER=20
AI_CONTEXT_TOKEN_BUDGET=3072
AI_MAX_OUTPUT_TOKENS=1024
AI_STREAM_POLL_SECONDS=0.15

PLUGIN_EXECUTION_MODE=sandbox
PLUGIN_SANDBOX_URL=http://plugin-sandbox:8091
PLUGIN_SANDBOX_API_KEY=$(New-RandomSecret)
PLUGIN_SANDBOX_TIMEOUT_SECONDS=10
PLUGIN_SANDBOX_MAX_PAYLOAD_BYTES=65536
PLUGIN_SANDBOX_MAX_OUTPUT_BYTES=65536

TURN_DOMAIN=$ServerAddress
TURN_PORT=3478
TURN_MIN_PORT=50000
TURN_MAX_PORT=50040
TURN_EXTERNAL_IP=$TurnExternalAddress
TURN_AUTH_SECRET=$(New-RandomSecret)
TURN_CREDENTIAL_TTL_SECONDS=3600
"@
    [IO.File]::WriteAllText($envPath, ($content.Trim() + [Environment]::NewLine), (New-Object Text.UTF8Encoding($false)))
    Write-Host ".env created: $envPath"
}

function Read-EnvironmentFile {
    if (-not (Test-Path -LiteralPath $envPath)) {
        throw '.env is missing. Run Initialize first.'
    }
    $values = @{}
    foreach ($line in Get-Content -LiteralPath $envPath) {
        $trimmed = $line.Trim()
        if (-not $trimmed -or $trimmed.StartsWith('#')) { continue }
        $separator = $trimmed.IndexOf('=')
        if ($separator -lt 1) { throw "Invalid .env line: $line" }
        $key = $trimmed.Substring(0, $separator).Trim()
        $value = $trimmed.Substring($separator + 1)
        if ($values.ContainsKey($key)) { throw "Duplicate .env key: $key" }
        $values[$key] = $value
    }
    return $values
}

function Assert-EnvironmentFile {
    $values = Read-EnvironmentFile
    $required = @(
        'POSTGRES_USER', 'POSTGRES_PASSWORD', 'POSTGRES_DB',
        'SYNAPSE_POSTGRES_USER', 'SYNAPSE_POSTGRES_PASSWORD', 'SYNAPSE_POSTGRES_DB',
        'CORE_API_SECRET_KEY', 'NEXUS_DOMAIN', 'NEXUS_ACME_EMAIL',
        'MATRIX_SERVER_NAME', 'MATRIX_REGISTRATION_SHARED_SECRET',
        'MATRIX_MACAROON_SECRET_KEY', 'MATRIX_FORM_SECRET',
        'OLLAMA_BASE_URL', 'OLLAMA_API_KEY', 'PLUGIN_SANDBOX_API_KEY',
        'TURN_DOMAIN', 'TURN_EXTERNAL_IP', 'TURN_AUTH_SECRET'
    )
    foreach ($key in $required) {
        if (-not $values.ContainsKey($key) -or [string]::IsNullOrWhiteSpace($values[$key])) {
            throw ".env key is missing: $key"
        }
        if ($values[$key] -match 'replace-with-|<[^>]+>') {
            throw ".env still contains a placeholder: $key"
        }
    }
    if ($values['MATRIX_SERVER_NAME'] -match '://|/') {
        throw 'MATRIX_SERVER_NAME must not contain protocol or path.'
    }
    foreach ($secretKey in @(
        'POSTGRES_PASSWORD', 'SYNAPSE_POSTGRES_PASSWORD', 'CORE_API_SECRET_KEY',
        'MATRIX_REGISTRATION_SHARED_SECRET', 'MATRIX_MACAROON_SECRET_KEY',
        'MATRIX_FORM_SECRET', 'OLLAMA_API_KEY', 'PLUGIN_SANDBOX_API_KEY',
        'TURN_AUTH_SECRET'
    )) {
        if ($values[$secretKey].Length -lt 20) {
            throw ".env secret is too short: $secretKey"
        }
    }
}

function Get-SynapseLocale {
    $json = Invoke-Compose -Arguments @('config', '--format', 'json') -Capture
    $config = $json | ConvertFrom-Json
    $adminUser = [string]$config.services.postgres.environment.POSTGRES_USER
    $maintenanceDatabase = [string]$config.services.postgres.environment.POSTGRES_DB
    $synapseDatabase = [string]$config.services.postgres.environment.SYNAPSE_POSTGRES_DB
    $escapedDatabase = $synapseDatabase.Replace("'", "''")
    $sql = "SELECT datcollate || '|' || datctype FROM pg_database WHERE datname = '$escapedDatabase'"
    $output = Invoke-Compose -Arguments @(
        'exec', '-T', 'postgres', 'psql',
        "--username=$adminUser",
        "--dbname=$maintenanceDatabase",
        '--tuples-only',
        '--no-align',
        "--command=$sql"
    ) -Capture
    return $output.Trim()
}

function Test-AiGateway {
    $values = Read-EnvironmentFile
    Write-Step 'Testing AI Gateway connectivity and authentication'
    & (Join-Path $PSScriptRoot 'test-ai-gateway-tailscale.ps1') `
        -GatewayBaseUrl $values['OLLAMA_BASE_URL'] `
        -ApiKey $values['OLLAMA_API_KEY']
    if ($LASTEXITCODE -ne 0) { throw 'AI Gateway test failed.' }
}

function Test-PublicEndpoints {
    $values = Read-EnvironmentFile
    $publicUrl = if ($values.ContainsKey('NEXUS_PUBLIC_URL')) {
        $values['NEXUS_PUBLIC_URL'].TrimEnd('/')
    }
    else {
        $port = if ($values.ContainsKey('NEXUS_HTTPS_PORT')) { [int]$values['NEXUS_HTTPS_PORT'] } else { 443 }
        Get-PublicUrl -HostName $values['NEXUS_DOMAIN'] -Port $port
    }
    if (-not (Get-Command curl.exe -ErrorAction SilentlyContinue)) {
        Write-Warning "curl.exe not found; public endpoint checks were skipped: $publicUrl"
        return
    }

    Write-Step "Waiting for public health endpoint: $publicUrl"
    $healthContent = $null
    for ($attempt = 1; $attempt -le 24; $attempt++) {
        $healthContent = & curl.exe --fail --silent --show-error --insecure --max-time 8 "$publicUrl/healthz" 2>$null
        if ($LASTEXITCODE -eq 0 -and ($healthContent | Out-String).Trim() -eq 'ok') { break }
        if ($attempt -eq 24) {
            throw "Public health endpoint did not become ready: $publicUrl/healthz"
        }
        Start-Sleep -Seconds 5
    }
    Write-Host '[OK] reverse proxy health'

    & curl.exe --fail --silent --show-error --insecure --max-time 10 "$publicUrl/api/health" | Out-Null
    if ($LASTEXITCODE -ne 0) { throw 'Backend public health check failed.' }
    Write-Host '[OK] backend health'

    $matrix = & curl.exe --fail --silent --show-error --insecure --max-time 10 "$publicUrl/_matrix/client/versions"
    if ($LASTEXITCODE -ne 0 -or ($matrix | Out-String) -notmatch '"versions"') {
        throw 'Matrix public health check failed.'
    }
    Write-Host '[OK] Matrix client endpoint'
}

function Invoke-Deploy {
    Assert-Prerequisites
    Assert-EnvironmentFile
    Write-Step 'Validating Docker Compose configuration'
    Invoke-Compose -Arguments @('config', '--quiet') | Out-Null
    Test-AiGateway

    if (-not $SkipBuild) {
        Write-Step 'Building service images'
        Invoke-Compose -Arguments @('build')
    }

    Write-Step 'Starting PostgreSQL and reconciling roles/databases'
    Invoke-Compose -Arguments @('up', '-d', 'postgres')
    Invoke-Compose -Arguments @('run', '--rm', 'postgres-bootstrap')

    $locale = Get-SynapseLocale
    if (-not $locale) {
        throw 'Synapse database locale could not be detected after postgres-bootstrap.'
    }
    if ($locale -ne 'C|C') {
        Write-Step "Repairing Synapse locale ($locale -> C|C) with backup"
        & powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot 'repair-synapse-collation.ps1') -ConfirmRepair
        if ($LASTEXITCODE -ne 0) { throw 'Synapse locale repair failed.' }
    }

    Write-Step 'Applying database migrations'
    Invoke-Compose -Arguments @('run', '--rm', 'migrate')

    Write-Step 'Starting the complete stack'
    Invoke-Compose -Arguments @('up', '-d')
    Invoke-Compose -Arguments @('ps', '-a')
    Test-PublicEndpoints
}

function Invoke-SafeGitUpdate {
    $git = Get-GitExecutable
    $stamp = (Get-Date).ToUniversalTime().ToString("yyyyMMdd-HHmmss'Z'")
    $dirty = (& $git status --porcelain --untracked-files=no | Out-String).Trim()
    if ($LASTEXITCODE -ne 0) { throw 'git status failed.' }
    if ($dirty) {
        Write-Step 'Saving tracked server changes before update'
        & $git stash push -m "nexus-server-auto-$stamp"
        if ($LASTEXITCODE -ne 0) { throw 'Local tracked changes could not be stashed.' }
        Write-Host "Tracked changes were preserved in git stash: nexus-server-auto-$stamp"
    }
    Write-Step 'Pulling origin/main with fast-forward only'
    & $git pull --ff-only origin main
    if ($LASTEXITCODE -ne 0) {
        throw 'git pull failed. Any automatic stash was preserved and was not popped.'
    }
}

function Show-Status {
    Assert-Prerequisites
    Assert-EnvironmentFile
    Invoke-Compose -Arguments @('ps', '-a')
}

function Invoke-Validation {
    Assert-Prerequisites
    Assert-EnvironmentFile
    Write-Step 'Validating Docker Compose configuration'
    Invoke-Compose -Arguments @('config', '--quiet') | Out-Null
    Test-AiGateway
    Write-Host '[OK] environment, Compose and AI Gateway validation completed'
}

function Invoke-Diagnose {
    Show-Status
    Write-Step 'Recent service logs'
    Invoke-Compose -Arguments @(
        'logs', '--tail', '120',
        'postgres', 'postgres-bootstrap', 'migrate', 'matrix',
        'backend', 'ai-worker', 'frontend', 'reverse-proxy'
    )
}

function Show-Help {
    @'
Nexus server manager

New server (run after git clone):
  powershell.exe -ExecutionPolicy Bypass -File .\scripts\nexus-server.ps1 -Action Initialize `
    -ServerAddress 25.49.22.166 -AcmeEmail you@domain.tld `
    -AiGatewayUrl http://25.31.233.158:8090

  The AI Gateway key is requested once with a hidden prompt.

Routine update:
  powershell.exe -ExecutionPolicy Bypass -File .\scripts\nexus-server.ps1 -Action Update

Other actions:
  -Action Configure  Generate .env only (new server)
  -Action Validate   Validate environment, Compose and AI Gateway
  -Action Deploy     Validate/build/bootstrap/migrate/start
  -Action Start      Start existing stack without build
  -Action Stop       Stop containers without deleting them or their volumes
  -Action Restart    Restart the existing stack
  -Action Status     Show all container states
  -Action Diagnose   Show states and recent logs
  -Action Backup     Create PostgreSQL backups
  -Action RepairDatabase  Back up and repair Synapse C/C locale
'@ | Write-Host
}

switch ($Action) {
    'Help' { Show-Help }
    'Configure' {
        Write-Step 'Creating a new server environment'
        New-EnvironmentFile
    }
    'Initialize' {
        Assert-Prerequisites
        Write-Step 'Creating a new server environment'
        New-EnvironmentFile
        Invoke-Deploy
    }
    'Deploy' { Invoke-Deploy }
    'Validate' { Invoke-Validation }
    'Update' {
        Assert-Prerequisites
        Invoke-SafeGitUpdate
        Invoke-Deploy
    }
    'Start' {
        Assert-Prerequisites
        Assert-EnvironmentFile
        Invoke-Compose -Arguments @('up', '-d')
        Invoke-Compose -Arguments @('ps', '-a')
    }
    'Stop' {
        Assert-Prerequisites
        Invoke-Compose -Arguments @('stop')
        Invoke-Compose -Arguments @('ps', '-a')
    }
    'Restart' {
        Assert-Prerequisites
        Assert-EnvironmentFile
        Invoke-Compose -Arguments @('restart')
        Invoke-Compose -Arguments @('ps', '-a')
    }
    'Status' { Show-Status }
    'Diagnose' { Invoke-Diagnose }
    'Backup' {
        Assert-Prerequisites
        Assert-EnvironmentFile
        & powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot 'backup-postgres.ps1')
        if ($LASTEXITCODE -ne 0) { throw 'PostgreSQL backup failed.' }
    }
    'RepairDatabase' {
        Assert-Prerequisites
        Assert-EnvironmentFile
        & powershell.exe -NoProfile -ExecutionPolicy Bypass `
            -File (Join-Path $PSScriptRoot 'repair-synapse-collation.ps1') `
            -ConfirmRepair -StartServices
        if ($LASTEXITCODE -ne 0) { throw 'Synapse database repair failed.' }
    }
}
